version: "3.8"

services:
  db:
    image: mysql:8.3
    container_name: investments-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: investments
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: investments-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://root:strongpassword@db:3306/investments
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: npm run dev

volumes:
  db_data:
